name: CD - Docker Hub Publish

on:
  push:
    branches: [ main, master ]
  workflow_run:
    workflows: ["CI - Test and Build"]
    branches: [ main, master ]
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'push' }}
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and push Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/persons-frontend:latest,${{ secrets.DOCKERHUB_USERNAME }}/persons-frontend:${{ github.sha }}
      
      - name: Build and push Backend
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/persons-backend:latest,${{ secrets.DOCKERHUB_USERNAME }}/persons-backend:${{ github.sha }}
      
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/persons-frontend
          short-description: "Frontend de l'application Persons Management"
          readme-filepath: ./frontend/README.md
      
      - name: Docker Hub Description for Backend
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/persons-backend
          short-description: "API Backend de l'application Persons Management"
          readme-filepath: ./backend/README.md
